### ISSUE TITLE
MacOS: v2.3.1+jdk21 throw error "ERROR_NO_SUCH_DEVICE" when activating

### ISSUE THREAD

**Issue by lehoanggiap** [slytechs-repos/jnetpcap-wrapper#63]
Hi, I'm stucking with the error  `ERROR_NO_SUCH_DEVICE` when running `pcap.activate()` in the example. Do you know how to resolve this issue, here are the full logs

```
Exception in thread "main" org.jnetpcap.PcapException: ERROR_NO_SUCH_DEVICE
	at org.jnetpcap.PcapException.throwIfNotOk(PcapException.java:65)
	at org.jnetpcap.PcapException.throwIfNotOk(PcapException.java:41)
	at org.jnetpcap.Pcap1_0.activate(Pcap1_0.java:443)
	at Application.main(Application.java:24)
```

Some information about my project may help you troubleshoot the issue

### Environment
- Java **21**
- libpcap **1.10.5**
- IntelliJ IDEA **2024.3** (Ultimate Edition)
- MacOS Sonoma **14.5**
- jnetpcap-wrapper **v2.3.1+jdk21**

### Code
```
List<PcapIf> devices = Pcap.findAllDevs();
try (Pcap pcap = Pcap.create(devices.get(0))) {
    pcap.activate();
    pcap.loop(1, (String msg, PcapHeader header, byte[] packet) -> {
        System.out.println(msg);
    }, "Capture Example");
}
```

### Note
I have followed your instruction in the [Wiki pages](https://github.com/slytechs-repos/jnetpcap/wiki) including setting the `--enable-native-access=ALL-UNNAMED -Djava.library.path=/opt/homebrew/Cellar/libpcap/1.10.5/lib` and enabling the capture privileges by running command `sudo chown $(whoami):admin /dev/bpf*`, but it still didn't help.

**Comment by SecureNetWizard** [comment]
Let me take a look. I did specifically address this issue in 2.3.1 in Pcap1_0::create method:

	at org.jnetpcap.Pcap1_0.activate(Pcap1_0.java:443)

**Comment by SecureNetWizard** [comment]
Please make sure you have `v2.3.1+jdk21` linked to your application. I can not replicate this issue, it is working in `v2.3.1` and `v2.3.1+jdk21`. Your short application included.

This was an issue with the previous version, which has fixed in this recent `v2.3.1` point release.

Please, let me know what you find.

**Comment by lehoanggiap** [comment]
Ok so let me try to upgrade to the new version to see whether it can fix or not.

**Comment by lehoanggiap** [comment]
Thanks @SecureNetWizard , upgrading to version 2.3.1 did help. I will close the issue
